### ISSUE TITLE
readme

### ISSUE THREAD

**Issue by brock** [ncsa/TorusVis#1]
Hey @opadron 

Is there anything you could add to the readme for this project?

**Comment by opadron** [comment]
Hi, @brock.

My employment at NCSA had concluded since releasing the TorusVis source code several months ago, and I no longer consider myself up-to-date on NCSA's plans for TorusVis moving forward.  I suggest you follow-up with Greg Bauer who oversees the Blue Waters application support group.  He may be able to identify resources within NCSA that may be brought to bear on TorusVis development.

For my part, I am open to continued TorusVis development, provided a source of funding.  If there is NCSA interest in continuing the project, or should you otherwise wish to discuss it further, I welcome you to get in touch with me.

**Comment by brock** [comment]
Okay thanks @opadron
